name          'ivanlei-apt_cacher_ng'
version       '1.0.0'
summary       'Puppet module for apt-cacher-ng'
description   'Puppet module for apt-cacher-ng'
source        'https://github.com/ivanlei/puppet-apt_cacher_ng.git'
project_page  'https://github.com/ivanlei/puppet-apt_cacher_ng'
license       'http://unlicense.org/'

dependency    'puppetlabs/stdlib', '>=4.1.0'
dependency    'puppetlabs/apt',    '>=1.2.0'
